# Generated by Django 3.1.3 on 2020-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantina', '0002_auto_20201110_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
